export const BUSINESS = {
  name: "Plomberie Rodriguez Diego",
  owner: "Diego Rodriguez",
  phone: "+33637759206",
  phoneDisplay: "06 37 75 92 06",
  email: "diego.rodriguez131100@gmail.com",
  notifEmail: "diego.rodriguez131100@gmail.com",
  logo: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/e429aeb88_logo.png",
  address: "3 Sq. Guy de Maupassant",
  city: "Port-de-Bouc",
  zip: "13110",
  fullAddress: "3 Sq. Guy de Maupassant, 13110 Port-de-Bouc",
  region: "Bouches-du-Rhône",
  hours: "Lundi – Vendredi : 8h – 18h30",
  hoursShort: "8h – 18h30",
  googleMapsUrl:
    "https://www.google.com/maps/place/Plomberie+Rodriguez+Diego/@43.4124742,4.9776117,17z/data=!3m1!4b1!4m6!3m5!1s0x12b61f9c2c01f7d3:0xd74d45f920397ae1!8m2!3d43.4124742!4d4.9801866!16s%2Fg%2F11j30q3132?hl=fr-FR&entry=ttu&g_ep=EgoyMDI2MDQwNy4wIKXMDSoASAFQAw%3D%3D",
  googleMapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2885.3!2d4.9801866!3d43.4124742!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12b61f9c2c01f7d3%3A0xd74d45f920397ae1!2sPlomberie%20Rodriguez%20Diego!5e0!3m2!1sfr!2sfr!4v1699000000000",
  googleReviewsUrl: "https://www.google.com/maps/place/Plomberie+Rodriguez+Diego/@43.4124742,4.9776117,17z/data=!3m1!4b1!4m6!3m5!1s0x12b61f9c2c01f7d3:0xd74d45f920397ae1!8m2!3d43.4124742!4d4.9801866!16s%2Fg%2F11j30q3132?hl=fr-FR&entry=ttu&g_ep=EgoyMDI2MDQwNy4wIKXMDSoASAFQAw%3D%3D",
  whatsapp: "33637759206",
  zones: [
    {
      name: "Port-de-Bouc",
      delay: "< 30 min",
      primary: true,
      slug: "port-de-bouc",
      postalCode: "13110",
      // hasPage: false → la page d'accueil est déjà la page Port-de-Bouc (évite le keyword cannibalization).
      hasPage: false,
      desc: "Ville principale d'intervention. Diego Rodriguez intervient dans toutes les rues et quartiers de Port-de-Bouc (13110) pour vos dépannages plomberie et travaux de carrelage.",
    },
    {
      name: "Martigues",
      delay: "< 35 min",
      primary: true,
      slug: "martigues",
      postalCode: "13500",
      hasPage: true,
      distanceKm: 10,
      population: "~50 000 habitants",
      desc: "Plombier à Martigues : fuite, débouchage, rénovation salle de bain. Intervention rapide dans toute la commune de Martigues et ses quartiers.",
      intro: "Surnommée la « Venise provençale », Martigues présente un parc immobilier varié : maisons anciennes en pierre dans le centre historique de Jonquières, L'Île et Ferrières, pavillons modernes en périphérie, copropriétés en bord d'étang. Diego Rodriguez, plombier installé à 10 minutes à Port-de-Bouc, intervient sur l'ensemble de la commune.",
      quartiers: ["Jonquières", "L'Île", "Ferrières", "Lavera", "Croix-Sainte", "La Couronne", "Carro", "Saint-Julien", "Saint-Pierre"],
      habitat: "Centre-ville ancien avec installations parfois d'époque (canalisations plomb ou cuivre à reprendre), quartiers pavillonnaires plus récents en périphérie, copropriétés des années 70-80 autour de l'étang de Berre.",
      specificites: "Eau calcaire qui marque les robinetteries et fatigue les chauffe-eau, dégâts d'humidité fréquents dans les bâtisses anciennes proches de l'eau, fuites sur canalisations enterrées dans les pavillons des années 70-80, débouchage de canalisations dans les centres anciens.",
      servicesPhares: ["depannage", "fuite", "renovation", "carrelage"],
      faq: [
        { q: "Combien de temps pour intervenir à Martigues depuis Port-de-Bouc ?", a: "Diego Rodriguez est basé à Port-de-Bouc, à environ 10 km de Martigues. Le temps d'intervention est généralement inférieur à 35 minutes selon la circulation, sur l'ensemble de la commune (Jonquières, L'Île, Ferrières, Lavera, La Couronne, Carro)." },
        { q: "Intervenez-vous dans le centre historique de Martigues (Jonquières, L'Île, Ferrières) ?", a: "Oui, nous intervenons régulièrement dans le centre ancien de Martigues. Les installations y sont souvent d'époque (plomb, cuivre, canalisations encastrées), ce qui demande de l'expertise pour les rénovations sans dégâts. Nous évaluons gratuitement vos travaux sur place." },
        { q: "Le calcaire abîme mon chauffe-eau à Martigues, pouvez-vous le remplacer ?", a: "Oui, le calcaire de la zone est un problème fréquent qui réduit la durée de vie des chauffe-eau et entartre les robinetteries. Nous remplaçons les chauffe-eau électriques, gaz ou thermodynamiques, avec possibilité d'installation d'un adoucisseur d'eau pour prolonger la durée de vie de vos équipements." },
        { q: "Faites-vous des rénovations complètes de salle de bain à Martigues ?", a: "Oui, c'est l'une de nos spécialités : plomberie, carrelage, faïence, pose de meubles sanitaires — un seul artisan pour tout votre chantier salle de bain à Martigues. Devis gratuit avec visite sur place." },
      ],
    },
    {
      name: "Fos-sur-Mer",
      delay: "< 40 min",
      primary: true,
      slug: "fos-sur-mer",
      postalCode: "13270",
      hasPage: true,
      distanceKm: 8,
      population: "~16 000 habitants",
      desc: "Artisan plombier à Fos-sur-Mer, disponible pour tous vos travaux de plomberie, carrelage et rénovation sanitaire.",
      intro: "Fos-sur-Mer est essentiellement composée de pavillons et lotissements récents, avec un centre ancien autour de l'hôtel de ville et du fort. Sa proximité avec Port-de-Bouc (8 km, moins de 15 minutes en voiture) permet à Diego Rodriguez d'intervenir rapidement pour vos urgences plomberie comme pour vos projets de rénovation.",
      quartiers: ["Centre-ville", "Le Mazet", "Mazet-Plage", "Saint-Gervais", "La Grand Plage", "Les Carabins"],
      habitat: "Majoritairement pavillonnaire (années 70 à aujourd'hui), avec quelques résidences récentes, lotissements et maisons individuelles. Quelques maisons de pêcheurs dans le centre historique.",
      specificites: "Installations souvent récentes mais soumises à un air salin agressif (corrosion des éléments extérieurs), problématiques de chauffe-eau dans les pavillons familiaux, remplacement de groupes de sécurité, rénovations de salles de bain dans les lotissements des années 80-90.",
      servicesPhares: ["chauffe-eau", "renovation", "sanitaire", "depannage"],
      faq: [
        { q: "Quel est le délai d'intervention à Fos-sur-Mer depuis Port-de-Bouc ?", a: "Fos-sur-Mer est à seulement 8 km de Port-de-Bouc — environ 15 minutes en voiture. Diego Rodriguez peut intervenir rapidement pour vos urgences plomberie sur l'ensemble de la commune (centre, Le Mazet, Saint-Gervais, La Grand Plage)." },
        { q: "Intervenez-vous sur les pavillons des lotissements de Fos-sur-Mer ?", a: "Oui, c'est même le type d'habitat majoritaire à Fos. Nous intervenons régulièrement sur les pavillons et villas des lotissements pour le dépannage, le remplacement de chauffe-eau, les recherches de fuite et les rénovations de salle de bain." },
        { q: "L'air marin abîme mes installations à Fos-sur-Mer, vous faites le remplacement ?", a: "Oui. La proximité de la mer accélère la corrosion des éléments extérieurs (robinetteries de jardin, chauffe-eau en garage non ventilé, raccords). Nous remplaçons ces équipements avec des matériaux adaptés à l'environnement salin." },
        { q: "Faites-vous le remplacement de chauffe-eau à Fos-sur-Mer ?", a: "Oui, nous remplaçons tous types de chauffe-eau (électrique, gaz, thermodynamique) à Fos-sur-Mer. Diagnostic, dépose de l'ancien, installation du neuf, mise en service. Devis gratuit." },
      ],
    },
    {
      name: "Istres",
      delay: "< 45 min",
      primary: true,
      slug: "istres",
      postalCode: "13800",
      hasPage: true,
      distanceKm: 15,
      population: "~44 000 habitants",
      desc: "Plombier à Istres : dépannage, installation sanitaire, remplacement chauffe-eau. Devis gratuit sur Istres et ses environs.",
      intro: "Istres est la plus grande commune voisine de Port-de-Bouc avec un parc immobilier hétérogène : centre historique autour de l'étang de l'Olivier, quartiers résidentiels modernes, copropriétés et lotissements. Diego Rodriguez intervient sur Istres et le village rattaché d'Entressen pour vos travaux de plomberie, dépannages et rénovations.",
      quartiers: ["Centre historique", "Le Prépaou", "Trigance", "Rassuen", "Entressen", "Le Ranquet", "La Romaniquette"],
      habitat: "Mix appartements en copropriété (centre et Prépaou), pavillons individuels (Trigance, Rassuen), maisons de village (centre historique et Entressen). Présence notable de logements liés à la base aérienne.",
      specificites: "Remplacements de chauffe-eau fréquents dans les copropriétés des années 70-80, fuites et reprises de plomberie dans les maisons de village du centre, créations et rénovations de salles de bain dans les pavillons familiaux.",
      servicesPhares: ["chauffe-eau", "fuite", "renovation", "sanitaire"],
      faq: [
        { q: "Intervenez-vous à Entressen et dans les villages rattachés à Istres ?", a: "Oui, Entressen fait partie intégrante de la commune d'Istres et nous nous y déplaçons aux mêmes conditions que sur le centre. Nous intervenons aussi à Rassuen, Le Prépaou, Trigance et tous les autres quartiers." },
        { q: "Combien de temps pour rejoindre Istres depuis Port-de-Bouc ?", a: "Istres est à environ 15 km de Port-de-Bouc, soit moins de 45 minutes d'intervention. Pour les urgences plomberie, appelez le 06 37 75 92 06 pour connaître nos disponibilités du jour." },
        { q: "Faites-vous les interventions dans les copropriétés à Istres ?", a: "Oui, nous intervenons aussi bien chez les particuliers que dans les copropriétés (en accord avec le syndic ou le propriétaire). Beaucoup de copropriétés du Prépaou ou de Trigance datent des années 70-80 et nécessitent des remplacements de chauffe-eau ou des reprises de plomberie." },
        { q: "Quel tarif pour un dépannage urgent à Istres ?", a: "Le tarif dépend de la nature de l'intervention. Nous fournissons un devis transparent avant tout démarrage de travaux. Pour une estimation, appelez-nous directement au 06 37 75 92 06." },
      ],
    },
    {
      name: "Saint-Mitre-les-Remparts",
      delay: "< 40 min",
      primary: true,
      slug: "saint-mitre-les-remparts",
      postalCode: "13920",
      hasPage: true,
      distanceKm: 12,
      population: "~6 000 habitants",
      desc: "Plombier artisan à Saint-Mitre-les-Remparts. Réparation fuite, débouchage, rénovation. Intervention sous 24h.",
      intro: "Saint-Mitre-les-Remparts, village médiéval fortifié au cœur de l'étang de Berre, conjugue maisons anciennes en pierre dans la cité historique et lotissements pavillonnaires en périphérie. Diego Rodriguez, plombier basé à Port-de-Bouc, intervient rapidement sur la commune pour vos dépannages et travaux de rénovation.",
      quartiers: ["Centre médiéval", "Massane", "Varage", "Plan-Fossan", "Les Étangs"],
      habitat: "Majoritairement maisons individuelles : bâtisses anciennes en pierre du centre médiéval (souvent rénovées partiellement, plomberie à reprendre), pavillons des années 80 à aujourd'hui dans les lotissements périphériques.",
      specificites: "Reprises de plomberie ancienne dans le centre fortifié (souvent installations partiellement modernisées il y a 20-30 ans), créations complètes de salles de bain dans les pavillons, problématiques de calcaire et d'eau dure typiques de la zone.",
      servicesPhares: ["renovation", "fuite", "carrelage", "sanitaire"],
      faq: [
        { q: "Combien de temps depuis Port-de-Bouc jusqu'à Saint-Mitre-les-Remparts ?", a: "Saint-Mitre-les-Remparts est à environ 12 km de Port-de-Bouc, soit 30 à 40 minutes d'intervention selon la circulation. Nous nous y déplaçons régulièrement pour vos dépannages et travaux planifiés." },
        { q: "Intervenez-vous dans le centre médiéval malgré les contraintes d'accès ?", a: "Oui, nous intervenons dans le centre fortifié de Saint-Mitre, en tenant compte des contraintes d'accès et de stationnement. Le matériel léger nécessaire est apporté à pied si besoin. Les installations anciennes du centre demandent une vraie expertise pour éviter d'abîmer la pierre." },
        { q: "Mon installation date des années 80, faites-vous la rénovation complète à Saint-Mitre ?", a: "Oui, nous reprenons régulièrement des installations plomberie partiellement modernisées il y a 20 ou 30 ans. Diego Rodriguez fait le diagnostic, propose un plan de rénovation cohérent (plomberie + carrelage + sanitaires) et intervient en tant qu'artisan unique." },
        { q: "Faites-vous un diagnostic plomberie avant achat immobilier à Saint-Mitre ?", a: "Oui, sur demande nous nous déplaçons pour évaluer l'état d'une installation avant achat (pression, fuites, vétusté du chauffe-eau, conformité des évacuations). Très utile pour négocier le prix ou prévoir le budget travaux." },
      ],
    },
    {
      name: "Sausset-les-Pins",
      delay: "< 50 min",
      primary: true,
      slug: "sausset-les-pins",
      postalCode: "13960",
      hasPage: true,
      distanceKm: 25,
      population: "~7 700 habitants",
      desc: "Besoin d'un plombier à Sausset-les-Pins ? Diego intervient rapidement pour toute urgence plomberie dans la commune.",
      intro: "Sausset-les-Pins, station balnéaire de la Côte Bleue, se caractérise par ses villas en bord de mer, ses résidences secondaires et son centre-ville animé autour du port. Diego Rodriguez intervient sur la commune pour vos urgences plomberie comme pour vos projets de rénovation, en particulier ceux liés à l'usure marine.",
      quartiers: ["Centre / Port", "Le Cap-Rousset", "La Plage", "Les Anges", "La Couronne (limite)"],
      habitat: "Beaucoup de villas individuelles et résidences secondaires (souvent inoccupées une partie de l'année, ce qui pose des questions d'hivernage), copropriétés résidentielles vue mer, quelques maisons de pêcheurs anciennes au port.",
      specificites: "Corrosion accélérée par l'air marin (robinetteries, chauffe-eau, raccords extérieurs), interventions à organiser autour de la présence intermittente des propriétaires de résidences secondaires, reprises après dégâts d'hivernage (canalisations gelées sur installations mal vidangées).",
      servicesPhares: ["depannage", "fuite", "chauffe-eau", "renovation"],
      faq: [
        { q: "Je suis propriétaire d'une résidence secondaire à Sausset, comment organiser une intervention ?", a: "Nous pouvons coordonner l'intervention avec vous à distance : vous nous fournissez un accès (gardien, voisin, clé) et nous vous envoyons un compte-rendu détaillé avec photos après chaque visite. Idéal pour les propriétaires absents la majeure partie de l'année." },
        { q: "Combien de temps pour intervenir à Sausset-les-Pins depuis Port-de-Bouc ?", a: "Sausset-les-Pins est à environ 25 km de Port-de-Bouc, soit environ 50 minutes d'intervention. Pour les urgences, contactez le 06 37 75 92 06 pour évaluer le délai du jour." },
        { q: "Faites-vous la mise en hivernage et la remise en eau des résidences secondaires ?", a: "Oui, c'est un service très demandé sur la Côte Bleue. Mise en hivernage à l'automne (vidange des canalisations, purge des chauffe-eau, isolation des points sensibles), remise en eau au printemps avec vérification de l'absence de fuite. Permet d'éviter les dégâts de gel coûteux." },
        { q: "L'air marin de la Côte Bleue abîme mes équipements, vous les remplacez ?", a: "Oui, la corrosion saline est un problème récurrent à Sausset (robinetteries extérieures, chauffe-eau en garage, raccords). Nous remplaçons par des équipements adaptés au milieu marin (inox, traitement anti-corrosion)." },
      ],
    },
    {
      name: "Carry-le-Rouet",
      delay: "< 50 min",
      primary: true,
      slug: "carry-le-rouet",
      postalCode: "13620",
      hasPage: true,
      distanceKm: 22,
      population: "~6 400 habitants",
      desc: "Plombier à Carry-le-Rouet, intervention pour fuites, canalisations, salle de bain. Devis gratuit et sans engagement.",
      intro: "Carry-le-Rouet, perle de la Côte Bleue avec son port et ses calanques, compte de nombreuses villas, résidences de standing et résidences secondaires. Diego Rodriguez se déplace sur la commune pour vos dépannages plomberie, rénovations de salles de bain et travaux liés aux contraintes du bord de mer.",
      quartiers: ["Le Port", "Sainte-Croix", "Le Rouet-Plage", "La Calanque", "Les Tamaris", "Le Centre"],
      habitat: "Villas individuelles avec jardin majoritaires, résidences secondaires fréquentes, copropriétés vue mer, quelques appartements en centre-ville. Niveau de gamme globalement supérieur à la moyenne du secteur.",
      specificites: "Salles de bain de standing à rénover, équipements haut de gamme (douche à l'italienne, baignoire balnéo, robinetterie premium), gestion de l'eau saline et de la corrosion, interventions à coordonner avec les gardiens et syndics pour les résidences secondaires.",
      servicesPhares: ["renovation", "sanitaire", "carrelage", "depannage"],
      faq: [
        { q: "Faites-vous l'installation d'équipements haut de gamme (douche italienne, baignoire balnéo) à Carry-le-Rouet ?", a: "Oui, c'est une demande fréquente à Carry. Nous installons des douches à l'italienne avec receveur extra-plat, des baignoires balnéo, des robinetteries premium et toute la robinetterie haut de gamme. Travail soigné, finitions impeccables." },
        { q: "Combien de temps pour rejoindre Carry-le-Rouet depuis Port-de-Bouc ?", a: "Carry-le-Rouet est à environ 22 km de Port-de-Bouc, soit environ 50 minutes selon la circulation (la route de la Côte Bleue peut être chargée en été). Pour les urgences, appelez le 06 37 75 92 06." },
        { q: "Intervenez-vous en copropriété ou pour les syndics à Carry-le-Rouet ?", a: "Oui, nous intervenons aussi bien chez les particuliers que pour les copropriétés et résidences. Nous coordonnons avec les syndics et gardiens pour faciliter l'accès et la planification, particulièrement pour les résidences secondaires." },
        { q: "Faites-vous le suivi pour résidence secondaire pendant mon absence ?", a: "Oui, nous pouvons organiser des visites de contrôle (vérification de l'absence de fuite, état du chauffe-eau, dépannage en cas de problème signalé par le voisinage). Compte-rendu photo systématique après chaque visite." },
      ],
    },
    { name: "Ensuès-la-Redonne", delay: "< 60 min", primary: false, slug: "ensues-la-redonne", postalCode: "13820", hasPage: false, desc: "Intervention plomberie à Ensuès-la-Redonne selon disponibilité." },
    { name: "Marignane", delay: "< 60 min", primary: false, slug: "marignane", postalCode: "13700", hasPage: false, desc: "Intervention plomberie à Marignane selon disponibilité." },
    { name: "Port-Saint-Louis-du-Rhône", delay: "< 60 min", primary: false, slug: "port-saint-louis-du-rhone", postalCode: "13230", hasPage: false, desc: "Intervention plomberie à Port-Saint-Louis-du-Rhône selon disponibilité." },
  ],
  services: [
    { id: "depannage", main: true, title: "Dépannage plomberie", emoji: "🔧", short: "Fuite, pression, canalisation : intervention rapide sur Port-de-Bouc.", desc: "Une fuite d'eau, une baisse de pression, un robinet qui ne ferme plus ? Plomberie Rodriguez Diego intervient rapidement à Port-de-Bouc et dans toute sa zone d'intervention pour régler vos problèmes de plomberie.", features: ["Diagnostic rapide sur place", "Réparation fuites visibles et cachées", "Remplacement robinets et joints", "Remise en pression des installations", "Devis gratuit avant intervention"] },
    { id: "renovation", main: true, title: "Création salle de bain", emoji: "🛁", short: "Votre salle de bain entièrement créée ou transformée par un seul artisan.", desc: "Plomberie, carrelage, faïence, pose de meubles sanitaires : Diego Rodriguez prend en charge l'intégralité de votre projet salle de bain, de la conception à la livraison. Un seul interlocuteur pour l'ensemble du chantier. Résultat garanti, propre et dans les délais convenus.", features: ["Conception & conseils en amont", "Dépose et évacuation ancienne salle de bain", "Plomberie et installation sanitaire", "Carrelage sol et mur / faïence", "Pose meubles, miroirs, accessoires"] },
    { id: "sanitaire", main: true, title: "Installation sanitaire", emoji: "🚿", short: "Pose WC, lavabo, douche, baignoire : installation soignée.", desc: "Pose ou remplacement de WC, lavabo, douche à l'italienne, baignoire balnéo… Plomberie Rodriguez Diego réalise l'ensemble de vos installations sanitaires avec soin. Travail propre, finitions impeccables, dans le respect des normes en vigueur.", features: ["Pose WC suspendu et à poser", "Installation douche à l'italienne", "Remplacement baignoire / vasque", "Robinetterie haut de gamme", "Respect des normes DTU"] },
    { id: "entretien", main: true, title: "Entretien plomberie", emoji: "🛡️", short: "Maintenance préventive pour éviter les pannes et dégâts.", desc: "Mieux vaut prévenir que guérir. Un entretien régulier de votre installation plomberie évite les pannes coûteuses et prolonge la durée de vie de vos équipements. Nous proposons des contrats d'entretien annuels adaptés aux particuliers et aux petites entreprises.", features: ["Inspection complète installation", "Détartrage robinets et chauffe-eau", "Contrôle pression et étanchéité", "Rapport d'état détaillé", "Contrat d'entretien annuel"] },
    { id: "fuite", title: "Recherche de fuite", emoji: "💧", short: "Détection non-destructive avec rapport pour votre assurance.", desc: "Une fuite peut causer des dégâts considérables si elle n'est pas traitée rapidement. Plomberie Rodriguez Diego utilise des techniques de détection de fuite non destructives pour localiser avec précision l'origine du problème, avec possibilité de recherche destructive et remise en état à l’identique.", features: ["Détection acoustique et thermique", "Zéro destruction inutile", "Rapport d'expertise pour assurance", "Localisation précise sous chape ou encastré", "Réparation dans la foulée"] },
    { id: "debouchage", title: "Débouchage", emoji: "🪣", short: "WC, évier, douche, canalisation : débouchage professionnel.", desc: "Un WC bouché, une douche qui ne s'écoule plus, un évier obstrué ? Notre matériel professionnel (furet électrique, hydrocureur) vient à bout de tous les bouchons, même les plus tenaces.", features: ["Débouchage WC & évier", "Hydrocurage canalisations", "Furet électrique professionnel", "Inspection caméra si nécessaire", "Entretien préventif canalisations"] },
    { id: "chauffe-eau", title: "Chauffe-eau & production d'eau chaude", emoji: "🔥", short: "Réparation, remplacement et installation de chauffe-eau.", desc: "Plus d'eau chaude ? Chauffe-eau qui fuit ? Nous intervenons sur tous types de chauffe-eau : électrique, thermodynamique, chauffe-eau solaire. Diagnostic rapide, remplacement ou réparation selon l'état de votre appareil.", features: ["Diagnostic chauffe-eau électrique et gaz", "Remplacement groupe de sécurité", "Installation chauffe-eau thermodynamique", "Conseil et devis comparatif", "Mise en service et contrôle"] },
    { id: "carrelage", title: "Carrelage & faïence", emoji: "🏗️", short: "Pose, rénovation et réfection carrelage sol et mur.", desc: "En complément de la plomberie, Diego Rodriguez est spécialisé dans la pose et rénovation de carrelage. Sol, mur, faïence de salle de bain, terrasse : un travail soigné, des joints parfaits, des finitions professionnelles.", features: ["Pose carrelage sol et mur", "Faïence salle de bain", "Dépose ancien carrelage", "Imperméabilisation bac douche", "Joints époxy haute résistance"] },
  ],
  reviews: [
    { name: "Marie-Hélène Raymond", city: "Port-de-Bouc", rating: 5, text: "Rénovation complète d'une salle de bain (faïences, carrelage, plomberie, peintures murs et plafond, pose des sanitaires / meubles / miroirs / branchements électriques / déplacement radiateur chauffage central par sèche-serviette). Travail impeccable, je recommande vivement !", date: "Mai 2025" },
    { name: "Camille V.", city: "Port-de-Bouc", rating: 5, text: "Je vous recommande vivement Monsieur Rodriguez Diego, il est intervenu à notre domicile en urgence pour une énorme fuite d'eau suite à un tuyau enterré cassé. Grâce à son efficacité et à son sérieux nous avons pu être dépannés rapidement.", date: "Janvier 2026" },
    { name: "Maxime Danet", city: "Port-de-Bouc", rating: 5, text: "Plombier très compétent, réactif et à l'écoute, avec d'excellents conseils. Il est intervenu rapidement, le travail est propre et soigné, et toutes ses explications étaient claires du début à la fin. Son sérieux et sa gentillesse font la différence.", date: "Décembre 2025" },
    { name: "Mehdi Brini", city: "Port-de-Bouc", rating: 5, text: "Intervention rapide et travail soigné. Le plombier a été ponctuel et très professionnel. Le problème a été réglé efficacement et le chantier laissé propre après son passage.", date: "Janvier 2026" },
    { name: "Vincent Peronne", city: "Port-de-Bouc", rating: 5, text: "Je vous recommande à 100% ce plombier qui a été réactif, présent sur place 1 heure après mon appel. Il a pris le temps de chercher la cause, consciencieux, professionnel, sympathique. Je ferai appel à lui sans hésiter.", date: "Février 2026" },
    { name: "A A", city: "Port-de-Bouc", rating: 5, text: "Merci à monsieur Rodriguez, il a été très disponible, à l'écoute, et bon professionnel.", date: "Mars 2026" },
    { name: "Gaet Gaet", city: "Port-de-Bouc", rating: 5, text: "Mr Rodriguez est très professionnel, efficace et réactif. Il a réparé définitivement et très rapidement une fuite au niveau de l'évacuation de l'évier. Je recommande.", date: "Janvier 2026" },
    { name: "Lisette Garcia", city: "Port-de-Bouc", rating: 5, text: "Un grand merci à ce jeune plombier, qui n'a pas hésité à venir en urgence après sa longue journée de travail pour déboucher les toilettes. Vraiment une personne dévouée, sympathique, avec un beau sourire. Je le conseille vivement.", date: "Février 2026" },
    { name: "Hajar Kapoor", city: "Port-de-Bouc", rating: 5, text: "Il a réussi à transformer mon débarras en une magnifique salle de bain. Je suis très satisfaite de son travail fait avec beaucoup de sérieux, il est à l'écoute de ce qu'on lui dit. J'ai très apprécié son professionnalisme.", date: "Décembre 2022" },
  ],
  faq: [
    { q: "Intervenez-vous en urgence à Port-de-Bouc ?", a: "Oui, nous intervenons aussi rapidement que possible sur Port-de-Bouc et les communes voisines pour toute urgence plomberie pendant nos horaires d'ouverture (8h–18h30, lundi au vendredi). Appelez directement le 06 37 75 92 06." },
    { q: "Quelles zones géographiques couvrez-vous ?", a: "Nous intervenons principalement à Port-de-Bouc, Martigues, Fos-sur-Mer, Istres, Saint-Mitre-les-Remparts, Sausset-les-Pins et Carry-le-Rouet. Nous nous déplaçons également à Ensuès-la-Redonne, Marignane et Port-Saint-Louis-du-Rhône." },
    { q: "Faites-vous des devis gratuits ?", a: "Oui, le devis est systématiquement gratuit et sans engagement. Contactez-nous par téléphone ou via le formulaire en ligne pour obtenir votre estimation personnalisée." },
    { q: "Intervenez-vous aussi pour le carrelage ?", a: "Oui, Diego Rodriguez est spécialisé dans la pose et rénovation de carrelage, en complément des travaux de plomberie. C'est un avantage majeur : un seul artisan pour l'intégralité de votre chantier salle de bain." },
    { q: "Êtes-vous assurés ?", a: "Oui, nous disposons d'une assurance responsabilité civile professionnelle. Toutes nos installations sont couvertes. N'hésitez pas à demander les justificatifs lors de la signature du devis." },
    { q: "Combien coûte un débouchage ?", a: "Le tarif dépend du type et de la complexité de l'intervention. Nous vous fournissons toujours un devis précis avant de commencer. Appelez-nous au 06 37 75 92 06 pour une estimation rapide." },
    { q: "Quel est votre délai d'intervention habituel ?", a: "Nous intervenons généralement sous 24 à 48h. Pour les demandes urgentes, nous faisons notre maximum pour répondre le jour même selon nos disponibilités." },
    { q: "Travaillez-vous le week-end ?", a: "Nous intervenons principalement du lundi au vendredi de 8h à 18h30. Des interventions le samedi matin sont possibles sur rendez-vous selon les disponibilités." },
  ],
  // Réalisations :
  //  - Si imageBefore ET imageAfter sont fournis → la réalisation apparaît
  //    dans le slider AVANT / APRÈS de la home (BeforeAfterShowcase).
  //  - Sinon → elle apparaît uniquement dans la galerie classique (champ "image").
  // Pour ajouter une nouvelle transformation, ajouter un objet avec les deux URLs.
  realizations: [
    // === Projet phare 1 : Rénovation totale ===
    {
      title: "Rénovation totale d'une salle de bain",
      city: "Port-de-Bouc",
      type: "Rénovation",
      imageBefore: "/images/realisations/sdb-baignoire-avant.png",
      imageAfter: "/images/realisations/sdb-baignoire-apres.webp",
      problem: "Salle de bain vieillissante : faïence rose des années 80, baignoire fatiguée, plomberie d'origine, agencement à revoir",
      solution: "Dépose totale, reprise plomberie complète, pose carrelage grand format ton pierre au sol et faïence claire au mur, baignoire neuve, paroi de douche vitrée, WC + bidet refaits, parquet bois imitation pour réchauffer l'ensemble",
      result: "Pièce méconnaissable : plus lumineuse, plus fonctionnelle, parfaitement étanche. Le client a gagné en confort comme en valeur immobilière",
      duration: "12 jours",
    },
    // === Projet phare 2 : Construction depuis le brut ===
    // Angle : montrer le savoir-faire complet, du chantier vide au rendu fini
    {
      title: "Création complète d'une salle de bain en couloir",
      city: "Port-de-Bouc",
      type: "Création",
      imageBefore: "/images/realisations/sdb-chantier-avant.png",
      imageAfter: "/images/realisations/sdb-chantier-apres.png",
      problem: "Espace vide à habiller : structure métallique apparente, câbles en attente, plomberie à créer de A à Z dans un volume étroit en couloir",
      solution: "Mise en place de la plomberie complète, pose du plafond suspendu avec spots LED, double mur en faïence motif vagues, baignoire encastrée, vasque sur plan, WC suspendu, miroir lumineux et tapis de sol",
      result: "Couloir transformé en salle de bain spa : le motif ondulé donne du caractère, l'éclairage indirect rappelle un hôtel, chaque mètre carré est exploité",
      duration: "9 jours",
    },
    // === Projet phare 3 : Rénovation autour de la baignoire ===
    {
      title: "Rénovation salle de bain — confort et lumière",
      city: "Port-de-Bouc",
      type: "Rénovation",
      imageBefore: "/images/realisations/sdb-renovation-avant.png",
      imageAfter: "/images/realisations/sdb-renovation-apres.png",
      problem: "Salle de bain familiale fonctionnelle mais datée, faïence ancienne, agencement et finitions à moderniser",
      solution: "Dépose et reprise complète plomberie, pose nouvelle baignoire et robinetterie, faïence et carrelage modernes, repositionnement sanitaires, finitions soignées",
      result: "La pièce gagne en lumière et en respiration. Confort retrouvé pour toute la famille",
      duration: "7 jours",
    },
    // === FIN DES PHARES (avant/après) ===
  ],

  // Galerie simple — chantiers récents en photo unique (apparaissent en bas de page)
  // À enrichir au fur et à mesure que Diego fournit des photos.
  // Format : { title, city, type, image, problem?, solution?, result? }
};

// Compatibilité : on garde des entrées image-unique dans realizations (le filtre dans Realisations.jsx
// les bascule automatiquement dans le feed simple si imageBefore + imageAfter ne sont pas là tous les deux)
// Galerie complémentaire — chantiers en photo unique (apparaissent dans le feed du bas)
BUSINESS.realizations.push(
  {
    title: "Salle de bain design en blanc",
    city: "Port-de-Bouc",
    type: "Création",
    image: "/images/realisations/sdb-design-blanche.png",
    problem: "Espace à équiper avec un parti pris épuré",
    solution: "Pose baignoire + WC, carrelage blanc grand format, finitions chromes",
    result: "Atmosphère lumineuse et facile à entretenir",
  },
  {
    title: "Remplacement chauffe-eau Atlantic",
    city: "Port-de-Bouc",
    type: "Chauffe-eau",
    image: "/images/realisations/service-chauffe-eau.png",
    problem: "Ancien cumulus en fin de vie, raccordement à reprendre",
    solution: "Pose d'un chauffe-eau Atlantic neuf, reprise des arrivées et du tableau électrique",
    result: "Eau chaude fiable, raccordements propres, prêt pour 10+ ans",
  }
);

