export const BUSINESS = {
  name: "Plomberie Rodriguez Diego",
  owner: "Diego Rodriguez",
  phone: "+33637759206",
  phoneDisplay: "06 37 75 92 06",
  email: "diego.rodriguez13@hotmail.fr",
  notifEmail: "plomberie.diego.rodriguez@gmail.com",
  logo: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/e429aeb88_logo.png",
  address: "3 Sq. Guy de Maupassant",
  city: "Port-de-Bouc",
  zip: "13110",
  fullAddress: "3 Sq. Guy de Maupassant, 13110 Port-de-Bouc",
  region: "Bouches-du-Rhône",
  hours: "Lundi – Vendredi : 8h – 18h30",
  hoursShort: "8h – 18h30",
  googleMapsUrl:
    "https://www.google.com/maps/place/Plomberie+Rodriguez+Diego/@43.4124742,4.9776117,17z/data=!3m1!4b1!4m6!3m5!1s0x12b61f9c2c01f7d3:0xd74d45f920397ae1!8m2!3d43.4124742!4d4.9801866!16s%2Fg%2F11j30q3132?hl=fr-FR&entry=ttu&g_ep=EgoyMDI2MDQwNy4wIKXMDSoASAFQAw%3D%3D",
  googleMapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2885.3!2d4.9801866!3d43.4124742!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12b61f9c2c01f7d3%3A0xd74d45f920397ae1!2sPlomberie%20Rodriguez%20Diego!5e0!3m2!1sfr!2sfr!4v1699000000000",
  googleReviewsUrl: "https://www.google.com/maps/place/Plomberie+Rodriguez+Diego/@43.4124742,4.9776117,17z/data=!3m1!4b1!4m6!3m5!1s0x12b61f9c2c01f7d3:0xd74d45f920397ae1!8m2!3d43.4124742!4d4.9801866!16s%2Fg%2F11j30q3132?hl=fr-FR&entry=ttu&g_ep=EgoyMDI2MDQwNy4wIKXMDSoASAFQAw%3D%3D",
  whatsapp: "33637759206",
  zones: [
    { name: "Port-de-Bouc", delay: "< 30 min", primary: true, desc: "Ville principale d'intervention. Diego Rodriguez intervient dans toutes les rues et quartiers de Port-de-Bouc (13110) pour vos dépannages plomberie et travaux de carrelage." },
    { name: "Martigues", delay: "< 35 min", primary: true, desc: "Plombier à Martigues : fuite, débouchage, rénovation salle de bain. Intervention rapide dans toute la commune de Martigues et ses quartiers." },
    { name: "Fos-sur-Mer", delay: "< 40 min", primary: true, desc: "Artisan plombier à Fos-sur-Mer, disponible pour tous vos travaux de plomberie, carrelage et rénovation sanitaire." },
    { name: "Istres", delay: "< 45 min", primary: true, desc: "Plombier à Istres : dépannage, installation sanitaire, remplacement chauffe-eau. Devis gratuit sur Istres et ses environs." },
    { name: "Saint-Mitre-les-Remparts", delay: "< 40 min", primary: true, desc: "Plombier artisan à Saint-Mitre-les-Remparts. Réparation fuite, débouchage, rénovation. Intervention sous 24h." },
    { name: "Sausset-les-Pins", delay: "< 50 min", primary: true, desc: "Besoin d'un plombier à Sausset-les-Pins ? Diego intervient rapidement pour toute urgence plomberie dans la commune." },
    { name: "Carry-le-Rouet", delay: "< 50 min", primary: true, desc: "Plombier à Carry-le-Rouet, intervention pour fuites, canalisations, salle de bain. Devis gratuit et sans engagement." },
    { name: "Ensuès-la-Redonne", delay: "< 60 min", primary: false, desc: "Intervention plomberie à Ensuès-la-Redonne selon disponibilité." },
    { name: "Marignane", delay: "< 60 min", primary: false, desc: "Intervention plomberie à Marignane selon disponibilité." },
    { name: "Port-Saint-Louis-du-Rhône", delay: "< 60 min", primary: false, desc: "Intervention plomberie à Port-Saint-Louis-du-Rhône selon disponibilité." },
  ],
  services: [
    { id: "depannage", main: true, title: "Dépannage plomberie", emoji: "🔧", short: "Fuite, pression, canalisation : intervention rapide sur Port-de-Bouc.", desc: "Une fuite d'eau, une baisse de pression, un robinet qui ne ferme plus ? Plomberie Rodriguez Diego intervient rapidement à Port-de-Bouc et dans toute sa zone d'intervention pour régler vos problèmes de plomberie.", features: ["Diagnostic rapide sur place", "Réparation fuites visibles et cachées", "Remplacement robinets et joints", "Remise en pression des installations", "Devis gratuit avant intervention"] },
    { id: "renovation", main: true, title: "Création salle de bain", emoji: "🛁", short: "Votre salle de bain entièrement créée ou transformée par un seul artisan.", desc: "Plomberie, carrelage, faïence, pose de meubles sanitaires : Diego Rodriguez prend en charge l'intégralité de votre projet salle de bain, de la conception à la livraison. Un seul interlocuteur pour l'ensemble du chantier. Résultat garanti, propre et dans les délais convenus.", features: ["Conception & conseils en amont", "Dépose et évacuation ancienne salle de bain", "Plomberie et installation sanitaire", "Carrelage sol et mur / faïence", "Pose meubles, miroirs, accessoires"] },
    { id: "sanitaire", main: true, title: "Installation sanitaire", emoji: "🚿", short: "Pose WC, lavabo, douche, baignoire : installation soignée.", desc: "Pose ou remplacement de WC, lavabo, douche à l'italienne, baignoire balnéo… Plomberie Rodriguez Diego réalise l'ensemble de vos installations sanitaires avec soin. Travail propre, finitions impeccables, dans le respect des normes en vigueur.", features: ["Pose WC suspendu et à poser", "Installation douche à l'italienne", "Remplacement baignoire / vasque", "Robinetterie haut de gamme", "Respect des normes DTU"] },
    { id: "entretien", main: true, title: "Entretien plomberie", emoji: "🛡️", short: "Maintenance préventive pour éviter les pannes et dégâts.", desc: "Mieux vaut prévenir que guérir. Un entretien régulier de votre installation plomberie évite les pannes coûteuses et prolonge la durée de vie de vos équipements. Nous proposons des contrats d'entretien annuels adaptés aux particuliers et aux petites entreprises.", features: ["Inspection complète installation", "Détartrage robinets et chauffe-eau", "Contrôle pression et étanchéité", "Rapport d'état détaillé", "Contrat d'entretien annuel"] },
    { id: "fuite", title: "Recherche de fuite", emoji: "💧", short: "Détection non-destructive avec rapport pour votre assurance.", desc: "Une fuite peut causer des dégâts considérables si elle n'est pas traitée rapidement. Plomberie Rodriguez Diego utilise des techniques de détection de fuite non destructives pour localiser avec précision l'origine du problème.", features: ["Détection acoustique et thermique", "Zéro destruction inutile", "Rapport d'expertise pour assurance", "Localisation précise sous chape ou encastré", "Réparation dans la foulée"] },
    { id: "debouchage", title: "Débouchage", emoji: "🪣", short: "WC, évier, douche, canalisation : débouchage professionnel.", desc: "Un WC bouché, une douche qui ne s'écoule plus, un évier obstrué ? Notre matériel professionnel (furet électrique, hydrocureur) vient à bout de tous les bouchons, même les plus tenaces.", features: ["Débouchage WC & évier", "Hydrocurage canalisations", "Furet électrique professionnel", "Inspection caméra si nécessaire", "Entretien préventif canalisations"] },
    { id: "chauffe-eau", title: "Chauffe-eau & cumulus", emoji: "🔥", short: "Réparation, remplacement et installation de chauffe-eau.", desc: "Plus d'eau chaude ? Chauffe-eau qui fuit ? Nous intervenons sur tous types de chauffe-eau : électrique, thermodynamique, chauffe-eau solaire. Diagnostic rapide, remplacement ou réparation selon l'état de votre appareil.", features: ["Diagnostic chauffe-eau électrique et gaz", "Remplacement groupe de sécurité", "Installation chauffe-eau thermodynamique", "Conseil et devis comparatif", "Mise en service et contrôle"] },
    { id: "carrelage", title: "Carrelage & faïence", emoji: "🏗️", short: "Pose, rénovation et réfection carrelage sol et mur.", desc: "En complément de la plomberie, Diego Rodriguez est spécialisé dans la pose et rénovation de carrelage. Sol, mur, faïence de salle de bain, terrasse : un travail soigné, des joints parfaits, des finitions professionnelles.", features: ["Pose carrelage sol et mur", "Faïence salle de bain et cuisine", "Dépose ancien carrelage", "Imperméabilisation bac douche", "Joints époxy haute résistance"] },
  ],
  reviews: [
    { name: "Marie-Hélène Raymond", city: "Port-de-Bouc", rating: 5, text: "Rénovation complète d'une salle de bain (faïences, carrelage, plomberie, peintures murs et plafond, pose des sanitaires / meubles / miroirs / branchements électriques / déplacement radiateur chauffage central par sèche-serviette). Travail impeccable, je recommande vivement !", date: "Mai 2025" },
    { name: "Camille V.", city: "Port-de-Bouc", rating: 5, text: "Je vous recommande vivement Monsieur Rodriguez Diego, il est intervenu à notre domicile en urgence pour une énorme fuite d'eau suite à un tuyau enterré cassé. Grâce à son efficacité et à son sérieux nous avons pu être dépannés rapidement.", date: "Janvier 2026" },
    { name: "Maxime Danet", city: "Port-de-Bouc", rating: 5, text: "Plombier très compétent, réactif et à l'écoute, avec d'excellents conseils. Il est intervenu rapidement, le travail est propre et soigné, et toutes ses explications étaient claires du début à la fin. Son sérieux et sa gentillesse font la différence.", date: "Décembre 2025" },
    { name: "Mehdi Brini", city: "Port-de-Bouc", rating: 5, text: "Intervention rapide et travail soigné. Le plombier a été ponctuel et très professionnel. Le problème a été réglé efficacement et le chantier laissé propre après son passage.", date: "Janvier 2026" },
    { name: "Vincent Peronne", city: "Port-de-Bouc", rating: 5, text: "Je vous recommande à 100% ce plombier qui a été réactif, présent sur place 1 heure après mon appel. Il a pris le temps de chercher la cause, consciencieux, professionnel, sympathique. Je ferai appel à lui sans hésiter.", date: "Février 2026" },
    { name: "A A", city: "Port-de-Bouc", rating: 5, text: "Merci à monsieur Rodriguez, il a été très disponible, à l'écoute, et bon professionnel.", date: "Mars 2026" },
    { name: "Gaet Gaet", city: "Port-de-Bouc", rating: 5, text: "Mr Rodriguez est très professionnel, efficace et réactif. Il a réparé définitivement et très rapidement une fuite au niveau de l'évacuation de l'évier. Je recommande.", date: "Janvier 2026" },
    { name: "Lisette Garcia", city: "Port-de-Bouc", rating: 5, text: "Un grand merci à ce jeune plombier, qui n'a pas hésité à venir en urgence après sa longue journée de travail pour déboucher les toilettes. Vraiment une personne dévouée, sympathique, avec un beau sourire. Je le conseille vivement.", date: "Février 2026" },
    { name: "Hajar Kapoor", city: "Port-de-Bouc", rating: 5, text: "Il a réussi à transformer mon débarras en une magnifique salle de bain. Je suis très satisfaite de son travail fait avec beaucoup de sérieux, il est à l'écoute de ce qu'on lui dit. J'ai très apprécié son professionnalisme.", date: "Décembre 2022" },
  ],
  faq: [
    { q: "Intervenez-vous en urgence à Port-de-Bouc ?", a: "Oui, nous intervenons aussi rapidement que possible sur Port-de-Bouc et les communes voisines pour toute urgence plomberie pendant nos horaires d'ouverture (8h–18h30, lundi au vendredi). Appelez directement le 06 37 75 92 06." },
    { q: "Quelles zones géographiques couvrez-vous ?", a: "Nous intervenons principalement à Port-de-Bouc, Martigues, Fos-sur-Mer, Istres, Saint-Mitre-les-Remparts, Sausset-les-Pins et Carry-le-Rouet. Nous nous déplaçons également à Ensuès-la-Redonne, Marignane et Port-Saint-Louis-du-Rhône." },
    { q: "Faites-vous des devis gratuits ?", a: "Oui, le devis est systématiquement gratuit et sans engagement. Contactez-nous par téléphone ou via le formulaire en ligne pour obtenir votre estimation personnalisée." },
    { q: "Intervenez-vous aussi pour le carrelage ?", a: "Oui, Diego Rodriguez est spécialisé dans la pose et rénovation de carrelage, en complément des travaux de plomberie. C'est un avantage majeur : un seul artisan pour l'intégralité de votre chantier salle de bain." },
    { q: "Êtes-vous assurés ?", a: "Oui, nous disposons d'une assurance responsabilité civile professionnelle. Toutes nos installations sont couvertes. N'hésitez pas à demander les justificatifs lors de la signature du devis." },
    { q: "Combien coûte un débouchage ?", a: "Le tarif dépend du type et de la complexité de l'intervention. Nous vous fournissons toujours un devis précis avant de commencer. Appelez-nous au 06 37 75 92 06 pour une estimation rapide." },
    { q: "Quel est votre délai d'intervention habituel ?", a: "Nous intervenons généralement sous 24 à 48h. Pour les demandes urgentes, nous faisons notre maximum pour répondre le jour même selon nos disponibilités." },
    { q: "Travaillez-vous le week-end ?", a: "Nous intervenons principalement du lundi au vendredi de 8h à 18h30. Des interventions le samedi matin sont possibles sur rendez-vous selon les disponibilités." },
  ],
  realizations: [
    { title: "Rénovation salle de bain", city: "Port-de-Bouc", type: "Rénovation", imageBefore: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/63301040d_salledebain_avant.png", imageAfter: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/c2ae3af7e_salledebain_apres.png", problem: "Salle de bain vétuste, plomberie entièrement à refaire", solution: "Création réseau plomberie, carrelage grand format, spots encastrés, sanitaires neufs", result: "Transformation totale — salle de bain moderne livrée clé en main" },
    { title: "Remplacement chauffe-eau thermodynamique", city: "Port-de-Bouc", type: "Chauffe-eau", image: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/bf241718f_chauffeeau.png", problem: "Ancien cumulus de 15 ans, consommation électrique élevée", solution: "Remplacement par chauffe-eau thermodynamique 200L Atlantic", result: "Économies de 60% sur la facture eau chaude, installation propre" },
    { title: "Installation douche à l'italienne", city: "Istres", type: "Installation", image: "https://media.base44.com/images/public/69d943d5cbef7978cbf110ac/a1bdaa1a3_salledebain.png", problem: "Baignoire trop encombrante, besoin d'accessibilité", solution: "Dépose baignoire, création receveur à carreler, pose carrelage grand format", result: "Douche à l'italienne spacieuse, accessible, finition haut de gamme" },
  ],
};
